### ISSUE TITLE
Extrapolate building upkeep state at the current time

### ISSUE THREAD

**Issue by valitas** [BartKieviet/Copilot#14]
Extrapolate the upkeep state of buildings based on the last known state, update timestamp, and current timestamp.

From Sweetness:
> One more thing, is there a way in the copilot table to have a second number (perhaps in parens) that describes what the upkeep would look like real time based on the information you uploaded to it?
> i.e. if I stock the buildings for 12 ticks can the co-pilot track the loss in upkeep goods as a projection of my last known information?

Personally, I wouldn't like this cluttering the already busy overview table. What I would like is a toggle button in the overview, to switch between e.g. "Last Known" and "Projected" displays. The former would be exactly what we have today; the latter would look the same but the numbers displayed will be the estimated amounts of commodities needed and produced, and the estimated number of ticks remaining, _at the current time_.

**Comment by BartKieviet** [comment]
I'll have to add this to the functions.js because #15 will also rely on this. I'll also move getTicks() there then.

**Comment by BartKieviet** [comment]
Done in bd7b08da170d6da884bf9ccd2dfacccc04e2c905

**Comment by BartKieviet** [comment]
Done in bd7b08da170d6da884bf9ccd2dfacccc04e2c905
