### ISSUE TITLE
Reorganise the source tree

### ISSUE THREAD

**Issue by valitas** [BartKieviet/Copilot#17]
Create a directory `chrome`, and move all the current files inside it. That way we can store a README, LICENCE, maybe docs, whatever extra stuff we may want at the top level, and not have all that included in the packaged extension in the Chrome Store (`chrome` would be the package dir; everything inside would be distributed inside the `crx` from the store).

Adding this as an issue so you're on notice that I intend to do this, @BartKieviet. It will be slightly annoying because you and I will have to remove and reinstall the extension from the new dir, so we will lose our current storage with all the configuration.

Let me know here when/if you're ok and ready for this.

**Comment by BartKieviet** [comment]
I'm up for it, at the moment my only app storage is for testing purposes.
