### ISSUE TITLE
Display the time buildings run out of upkeep

### ISSUE THREAD

**Issue by valitas** [BartKieviet/Copilot#5]
From Sweetness: "I actually prefer what time they run out of F/W rather than number of ticks."

Maybe an option to display this beside the number of ticks, rather than instead?

**Comment by BartKieviet** [comment]
62a57d2 now adds the level to the overview. A small step from this to the ticks.

**Comment by valitas** [comment]
This was arguably closed in 7a6f320756482e687e1dae19dcfd97b244420219. Further, the functionality added when #14 is implemented will pretty much supersede this.
